import streamlit as st
from io import BytesIO
import pandas as pd
from fpdf import FPDF
import re
import io
# 1. Cached File Loader: Reads uploaded CSV or Excel files and caches them in memory to make the app faster
@st.cache_data(show_spinner=False)
def load_trial_balance_file(file_bytes, file_name):
    try:
        if file_name.endswith('.csv'):
            df_raw = pd.read_csv(BytesIO(file_bytes), header=None)
            sheet_name = None
        else:
            xls = pd.ExcelFile(BytesIO(file_bytes))
            sheet_name = xls.sheet_names[0]
            df_raw = pd.read_excel(BytesIO(file_bytes), sheet_name=sheet_name, header=None)
        return df_raw, sheet_name
    except Exception as e:
        return None, str(e)
    
#Clean numbers: Removes currency symbols, commas, and handles negative values in brackets (e.g., "(1,000)" -> -1000.0)
def clean_number(value_str):
    if pd.isna(value_str):
        return 0.0
    if isinstance(value_str, (int, float)):
        return float(value_str)
    value_str = str(value_str).strip()
    if value_str.startswith("(") and value_str.endswith("("):
        value_str = "-" + value_str[1:-1]
    value_str = re.sub(r"[,\s]", "", value_str)
    try:
        return float(value_str)
    except:
        return 0.0
#Guard Check: catches if someone mistakenly uploads a balance sheet file instead of a trial balance
def validate_trial_balance_structure(df):
    """Detects if the user accidentally uploaded a trial balance into the balance sheet tab."""
    text_content = df.to_string().lower()
    trial_balance_markers = ["unadjusted debit", "adjustments debit", "trial balance worksheet", "adjusted debit"]
    if "current assets" in text_content and "unadjusted debit" not in text_content and "debit" not in text_content:
        return False, " **Document Type Mismatch:** This appears to be a Balance sheet, but you are in the Trial Balance section. Please switch to the Balance Sheet section."
    return True, ""    
# PDF Generation Function
def generate_pdf_report(total_debits, total_credits, difference, is_balanced, summary_df):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "Trial Balance Audit Report", ln=True, align="center")
    
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 6, f"Prepared by: {firm_name} | Accountant: {preparer_name}", ln=True, align="center")
    pdf.cell(0, 6, f"Client: {client_name} {entity_type}", ln=True, align="center")
    pdf.set_font("Arial", "", 10)
    pdf.cell(0, 6, "Generated by Finalizer SaaS (ZAR)", ln=True, align="center")
    pdf.ln(8)
    # Validation Section Summary
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Executive Summary & Validation", ln=True)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 6, f"Total Debits: R {total_debits:,.2f}", ln=True)
    pdf.cell(0, 6, f"Total Credits: R {total_credits:,.2f}", ln=True)
    pdf.cell(0, 6, f"Difference: R {difference:,.2f}", ln=True)
    status_text = "Status: Balanced (Verified)" if is_balanced else "Status: Out of Balance"
    pdf.cell(0, 6, status_text, ln=True)
    pdf.ln(10)
    # Account Summary Table Header
    if summary_df is not None:
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 8, "Account Summary Breakdown", ln=True)
        pdf.set_font("Arial", "B", 10)
        pdf.cell(80, 8, "Account Name", 1)
        pdf.cell(35, 8, "Total Debit", 1)
        pdf.cell(35, 8, "Total Credit", 1)
        pdf.cell(40, 8, "Net Balance", 1)
        pdf.ln()
        
        pdf.set_font("Arial", "", 9)
        for _, row in summary_df.iterrows():
            account_name = str(row.iloc[0])[:35]  # truncate long names
            t_debit = f"{row['Total Debit']:,.2f}"
            t_credit = f"{row['Total Credit']:,.2f}"
            net_bal = f"{row['Net Balance']:,.2f}"
            
            pdf.cell(80, 6, account_name, 1)
            pdf.cell(35, 6, t_debit, 1)
            pdf.cell(35, 6, t_credit, 1)
            pdf.cell(40, 6, net_bal, 1)
            pdf.ln()
    return pdf.output(dest='S').encode('latin1')
#UI: handles file uploads, sidebar settings, and creates a report download
def trial_balance_ui():
    st.title("Finalizer | SA Trial Balance Analyzer")
    st.caption("Verify your financial documents instantly with automated parsing and compliance checks.")
    #sidebar: lets the accountant customize company branding and legal entity type
    st.sidebar.markdown("---")
    st.sidebar.markdown("### Report Name Branding (ZAR)")
    firm_name = st.sidebar.text_input("Accounting Firm Name", value="My Accounting Firm Inc.")
    preparer_name = st.sidebar.text_input("Preparer Name", value="Professional Accountant")
    client_name = st.sidebar.text_input("Client Company Name", value="Client Name")
    entity_type = st.sidebar.selectbox("Legal Entity Type", ["(Pty) Ltd", "CC", "Inc.", "Sole Prop", "Trust"])
    uploaded_file = st.file_uploader("Upload your trial balance file", type=["csv", "xlsx", "xls"], key="tb_uploader")
    
    if not uploaded_file:
        st.info("Please upload a trial balance file (CSV or Excel).")
        return
    
    with st.spinner("Processing file..."):
        try:
            if uploaded_file.name.endswith(".csv"):
                df = pd.read_csv(uploaded_file, header=None)
                sheet_name = None
            else:
                xls = pd.ExcelFile(uploaded_file)
                sheet_name = xls.sheet_names[0]
                df_raw = pd.read_excel(uploaded_file, sheet_name=sheet_name, header=None)
        except Exception as e:
            st.error(f"Failed to read file: {e}")
            return
        if df_raw.empty:
            st.markdown("Uploaded file is empty.")
            return
        
        is_valid, error_msg = validate_trial_balance_structure(df_raw)
        if not is_valid:
            st.error(error_msg)
            return
        #Find where table header row starts        
        header_row_idx = 0
        for idx, row in df_raw.iterrows():
            row_str = " ".join([str(val) for val in row.values if pd.notna(val)]).lower()
            if ('debit' in row_str or 'dr' in row_str) and ('credit' in row_str or 'cr' in row_str or 'account' in row_str):
                header_row_idx = idx
                break
        try:
            if uploaded_file.name.endswith(".csv"):
                df = pd.read_csv(uploaded_file, skiprows=header_row_idx)
            else:
                df = pd.read_excel(uploaded_file, sheet_name=sheet_name, skiprows=header_row_idx)
        except Exception as e:
            st.error(f"Failed to parse file structure: {e}")
            return
        df.columns = df.columns.astype(str).str.strip()
        #Detect the debit, credit and account description columns automatically
        debit_col = None
        credit_col = None
        account_col = None
        for col in df.columns:
            col_lower = str(col).lower()
            if ("debit" in col_lower or col_lower == "dr") and not debit_col:
                debit_col = col
            elif ("credit" in col_lower or col_lower == "cr") and not credit_col:
                credit_col = col
            elif ("account" in col_lower or "description" in col_lower or "name" in col_lower) and not account_col:
                account_col = col
                
        if debit_col is None or credit_col is None:
            st.error("Could not find 'Debit' or 'Credit' columns. Detected columns: {list(df.columns)}")
            return
        #Clean up account rows by removing empty rows or table rows
        if account_col:
            df = df[df[account_col].notna()].copy()
            exclude_keywords = ["total", "status", "tip", "difference"]
            def is_valid_account(val):
                val_str = str(val).lower()
                return not any(kw in val_str for kw in exclude_keywords)
            df = df[df[account_col].apply(is_valid_account)]
    #Clean and convert the debit and credit numbers into proper decimals
    df["Debit_Clean"] = df [debit_col].apply(clean_number)
    df["Credit_Clean"] = df [credit_col].apply(clean_number)
    #Check any unusual data entries (negative numbers, zeros, or duplicates)
    neg_debits = df[df["Debit_Clean"] < 0]
    neg_credits = df[df["Credit_Clean"] < 0]
    zero_balances = df[(df["Debit_Clean"] == 0) & (df["Credit_Clean"] == 0)]
    duplicate_accounts = None
    if account_col:
        duplicate_accounts = df[df.duplicated(subset=[account_col], keep=False)]
    #Check if the trial balance balances    
    total_debits = df["Debit_Clean"].sum()
    total_credits = df["Credit_Clean"].sum()
    difference = total_debits - total_credits
    debit_credit_ratio = (total_debits / total_credits) if total_credits > 0 else 0.0
    is_balanced = abs(difference) < 0.01
    #group accounts together for the summary table breakdown
    if account_col:
        df["Net_Balance"] = df["Debit_Clean"] - df["Credit_Clean"]
        summary_df = df.groupby(account_col).agg({
            "Debit_Clean": "sum",
            "Credit_Clean": "sum",
            "Net_Balance": "sum"
        }).reset_index()
        summary_df.columns = [account_col, "Total Debit", "Total Credit", "Net Balance"]
        summary_df["% of Total Debits"] = (summary_df["Total Debit"] / total_debits * 100).fillna(0)
        summary_df["% of Total Credits"] = (summary_df["Total Credit"] / total_credits * 100).fillna(0)
    else:
        summary_df = None
    #display raw data table inside an expander box    
    with st.expander("Raw Trial Balance Data"):
        st.dataframe(df)
    #display summary  by account with color highlighting for large amounts    
    with st.expander("Summary by Account"):
        if summary_df is not None:
            def highlight_large_values(val):
                color = ''
                if isinstance(val, (int, float)):
                    if abs(val) > 100000:
                        color = 'background-color: #ffcccc'
                return color
            st.dataframe(summary_df.style.map(highlight_large_values))
        else:
            st.info("No account/description column found for summary.")
    #display validation checks(warnings, totals, and balance status)        
    with st.expander("Validation"):
        if not neg_debits.empty:
            st.warning(f"Found {len(neg_debits)} debit entries with negative values.")
        if not neg_credits.empty:
            st.warning(f"Found {len(neg_credits)} credit entries with negative values.")
        if not zero_balances.empty:
            st.warning(f"Found {len(zero_balances)} entries with zero debit and credit.")
        if duplicate_accounts is not None and not duplicate_accounts.empty:
            st.warning(f"Found {len(duplicate_accounts)} duplicate_accounts entries.")
            
        st.markdown(f"**Total Debits:** R{total_debits:,.2f}")
        st.markdown(f"**Total Credits:** R{total_credits:,.2f}")
        st.markdown(f"**Debit-to-Credit Ratio:** {debit_credit_ratio:,.3f}")
        if abs(difference) < 0.01:
            st.success("Trial Balance is balanced.")
        else:
            st.error(f"Trial Balance is not balanced. Difference: R{difference:,.2f}")
    
    #prepare data for downloading cleaned files
    if account_col:
        to_download = df[[account_col, "Debit_Clean", "Credit_Clean"]].copy()
        to_download.columns = ["Account", "Debit", "Credit"]
    else:
        to_download = df[["Debit_Clean", "Credit_Clean"]].copy()
        to_download.columns = ["Debit", "Credit"]
        
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        to_download.to_excel(writer, index=False, sheet_name="Cleaned Trial Balance")
    excel_data = output.getvalue()
    #download buttons for both excel and pdf audit report
    col1, col2 = st.columns(2)
    with col1:
        st.download_button(
            label="Download Cleaned Trial Balance (Excel)",
            data=excel_data,
            file_name="cleaned_trial_balance.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    with col2:
        pdf_bytes = generate_pdf_report(total_debits, total_credits, difference, is_balanced, summary_df)
        st.download_button(
            label="Download PDF Audit Report",
            data=pdf_bytes,
            file_name="audit_report.pdf",
            mime="application/pdf"
        )

if __name__ == "__main__":
    trial_balance_ui()
    
    
    
    
    
    
    
    
    
    
    
    
